from setuptools import setup

setup(
    name="ReinforcementLearningWithDemonstration",
    version="0.1",
    description="Explore different algorithm that deals with demonstrations.",
    packages=["simulators", "algorithms"],
    requires=["setuptools", "wheel"],
    install_requires=[
        "backcall==0.2.0",
        "click==8.0.3",
        "cloudpickle==2.0.0",
        "cycler==0.11.0",
        "debugpy==1.5.1",
        "decorator==5.1.0",
        "dill==0.3.4",
        "docopt==0.6.2",
        "EasyProcess==0.3",
        "entrypoints==0.3",
        "ffmpeg-python==0.2.0",
        "fonttools==4.28.3",
        "future==0.18.2",
        "gym==0.21.0",
        "ipython==7.30.1",
        "jedi==0.18.1",
        "joblib==1.1.0",
        "jupyter-client==7.1.0",
        "jupyter-core==4.9.1",
        "kiwisolver==1.3.2",
        "matplotlib==3.5.0",
        "matplotlib-inline==0.1.3",
        "mypy-extensions==0.4.3",
        "nest-asyncio==1.5.4",
        "numpy==1.21.4",
        "packaging==21.3",
        "pandas==1.3.4",
        "parso==0.8.3",
        "pathspec==0.9.0",
        "pexpect==4.8.0",
        "pickleshare==0.7.5",
        "Pillow==8.4.0",
        "platformdirs==2.4.0",
        "prompt-toolkit==3.0.23",
        "ptyprocess==0.7.0",
        "pygame==2.1.0",
        "Pygments==2.10.0",
        "pyparsing==3.0.6",
        "python-dateutil==2.8.2",
        "pytz==2021.3",
        "PyVirtualDisplay==2.2",
        "pyzmq==22.3.0",
        "rlberry==0.1",
        "scipy==1.7.3",
        "seaborn==0.11.2",
        "setuptools-scm==6.3.2",
        "six==1.16.0",
        "tomli==1.2.2",
        "tornado==6.1",
        "traitlets==5.1.1",
        "typing_extensions==4.0.1",
        "wcwidth==0.2.5",
    ],
    extras_require={"dev": ["tqdm", "ipykernel", "black"]},
)
